### ISSUE TITLE
You cannot serialize or unserialize PDO instances

### ISSUE THREAD

**Issue by nynka** [zend-server-extensions/Z-Ray-ZF1#2]
I get this when using Z-Ray with my ZF1 applications. I does not give a proper backtrace so I can't really tell what's going on here. If I turn of Z-Ray everything works fine.

```Uncaught exception 'PDOException' with message 'You cannot serialize or unserialize PDO instances'```

Only backtrace is:
```
throw() at ..app\vendor\zendframework\zendframework1\library\Zend\Controller\Front.php
__sleep() at ..app\vendor\zendframework\zendframework1\library\Zend\Application\Bootstrap\Bootstrap.php: 105
dispatch() at ..app\vendor\zendframework\zendframework1\library\Zend\Application\Bootstrap\Bootstrap.php: 105
run() at ..app\vendor\zendframework\zendframework1\library\Zend\Application.php: 382
run() at ..app\public\index.php: 39

**Comment by amitdar** [comment]
Thanks for the report, we are working on a solution for the generic "cannot serialize" issue. If you have any additional info, or you can give us look at your application it would be helpful.

**Comment by jamesj2** [comment]
I got tired of waiting for an official fox for this issue.  I copied makeArraySerializable() from the fix in ZF2/zray.php.  And since ArrayUtils::iteratorToArray isn't included in ZF1 I included that as well.  So far it's working for me.  If you want to give it a try you can go [here](https://github.com/jamesj2/Z-Ray-ZF1/tree/serialize-fix).

**Comment by amitdar** [comment]
Thank you, this fix helps a lot. I've merged it into ZF1 official repo.
